import type { Entity } from './schemas';
export const catalog: Record<Entity, { title: string; description: string; fields: string[] }> = {
  organization: {
    title: 'Profil koperasi',
    description: 'Identitas dan awal rencana kerja Anda.',
    fields: [
      'title',
      'village',
      'district',
      'regency',
      'province',
      'manager',
      'start_date',
      'target_date',
    ],
  },
  workstreams: {
    title: 'Proyek & bidang kerja',
    description: 'Satu tempat untuk tujuan, catatan, dan tugas setiap proyek.',
    fields: [
      'title',
      'code',
      'description',
      'assignee',
      'start_date',
      'target_date',
      'color',
      'notes',
    ],
  },
  milestones: {
    title: 'Milestone',
    description: 'Hasil penting yang perlu dicapai dalam tiap tahap.',
    fields: ['title', 'workstream_id', 'due_date', 'actual_date', 'notes'],
  },
  'work-items': {
    title: 'Tugas',
    description: 'Ubah rencana menjadi langkah kerja yang jelas.',
    fields: [
      'title',
      'description',
      'workstream_id',
      'milestone_id',
      'unit_id',
      'assignee',
      'start_date',
      'due_date',
      'status',
      'priority',
      'poac',
      'recurrence',
      'subtasks',
      'dependencies',
      'link',
      'notes',
    ],
  },
  units: {
    title: 'Gerai',
    description: 'Pantau kesiapan pembukaan gerai secara bertahap.',
    fields: [
      'title',
      'kind',
      'assignee',
      'location',
      'status',
      'physical',
      'equipment',
      'sop',
      'staff',
      'link',
      'notes',
    ],
  },
  checklist: {
    title: 'Kesiapan',
    description: 'Periksa kelengkapan dan simpan bukti pekerjaan.',
    fields: [
      'title',
      'workstream_id',
      'unit_id',
      'dimension',
      'required',
      'status',
      'evidence',
      'link',
    ],
  },
  stakeholders: {
    title: 'Pemangku kepentingan',
    description: 'Jaga koordinasi dengan pengurus, dinas, dan mitra.',
    fields: ['title', 'category', 'contact', 'influence', 'interest', 'last_contact', 'follow_up'],
  },
  interactions: {
    title: 'Riwayat interaksi',
    description: 'Catat hasil kontak dan tindak lanjut.',
    fields: ['title', 'stakeholder_id', 'date', 'notes', 'follow_up'],
  },
  meetings: {
    title: 'Rapat & notulen',
    description: 'Simpan agenda, pembahasan, keputusan, dan tindak lanjut.',
    fields: ['title', 'date', 'time', 'participants', 'agenda', 'minutes'],
  },
  decisions: {
    title: 'Keputusan',
    description: 'Jejak keputusan beserta alasan dan sumbernya.',
    fields: ['title', 'meeting_id', 'date', 'reason', 'link'],
  },
  documents: {
    title: 'Dokumen & legalitas',
    description: 'Registri dokumen dan masa berlakunya.',
    fields: ['title', 'kind', 'number', 'issued_date', 'expires_date', 'status', 'link', 'notes'],
  },
  risks: {
    title: 'Risiko',
    description: 'Kenali hambatan sebelum menjadi masalah.',
    fields: ['title', 'probability', 'impact', 'mitigation', 'assignee', 'review_date', 'status'],
  },
  issues: {
    title: 'Isu lapangan',
    description: 'Catat masalah nyata dan langkah penyelesaiannya.',
    fields: ['title', 'description', 'assignee', 'due_date', 'status'],
  },
  staff: {
    title: 'Tim gerai',
    description: 'Daftar petugas, peran, dan penempatan.',
    fields: ['title', 'role', 'unit_id', 'status'],
  },
  trainings: {
    title: 'Pelatihan',
    description: 'Pantau kesiapan petugas dan pelatihan wajib.',
    fields: ['title', 'staff_id', 'date', 'required', 'status', 'notes'],
  },
  journal: {
    title: 'Jurnal kerja',
    description: 'Catatan harian dan kunjungan lapangan.',
    fields: ['title', 'date', 'notes', 'unit_id', 'work_item_id', 'stakeholder_id'],
  },
};
export const labels: Record<string, string> = {
  title: 'Nama / judul',
  village: 'Desa',
  district: 'Kecamatan',
  regency: 'Kabupaten',
  province: 'Provinsi',
  manager: 'Nama manajer',
  start_date: 'Tanggal mulai',
  target_date: 'Target pembukaan',
  code: 'Kode',
  color: 'Warna',
  description: 'Uraian',
  workstream_id: 'Proyek / bidang kerja',
  milestone_id: 'Milestone',
  unit_id: 'Gerai',
  assignee: 'Penanggung jawab',
  due_date: 'Tenggat',
  status: 'Status',
  priority: 'Prioritas',
  poac: 'Kategori POAC',
  recurrence: 'Pengulangan',
  subtasks: 'Subtugas',
  dependencies: 'Prasyarat',
  link: 'Tautan bukti / berkas',
  notes: 'Catatan',
  actual_date: 'Tanggal tercapai',
  kind: 'Jenis',
  location: 'Lokasi',
  physical: 'Kondisi fisik',
  equipment: 'Peralatan',
  sop: 'Kesiapan SOP',
  staff: 'Kesiapan petugas',
  dimension: 'Dimensi',
  required: 'Wajib',
  evidence: 'Bukti pekerjaan',
  category: 'Kategori',
  contact: 'Kontak profesional',
  influence: 'Pengaruh (1–5)',
  interest: 'Minat (1–5)',
  last_contact: 'Kontak terakhir',
  follow_up: 'Tindak lanjut',
  stakeholder_id: 'Pemangku kepentingan',
  date: 'Tanggal',
  time: 'Waktu WIB',
  participants: 'Peserta',
  agenda: 'Agenda',
  minutes: 'Notulen',
  meeting_id: 'Rapat',
  reason: 'Alasan keputusan',
  number: 'Nomor dokumen',
  issued_date: 'Tanggal terbit',
  expires_date: 'Berlaku sampai',
  probability: 'Peluang (1–5)',
  impact: 'Dampak (1–5)',
  mitigation: 'Mitigasi',
  review_date: 'Tanggal tinjau',
  role: 'Peran',
  staff_id: 'Petugas',
  work_item_id: 'Tugas terkait',
};
export const references: Record<string, Entity> = {
  issue_id: 'issues',
  workstream_id: 'workstreams',
  milestone_id: 'milestones',
  unit_id: 'units',
  stakeholder_id: 'stakeholders',
  meeting_id: 'meetings',
  staff_id: 'staff',
  work_item_id: 'work-items',
};
export const options: Record<string, string[]> = {
  'work-items.status': ['rencana', 'proses', 'selesai', 'dibatalkan'],
  'checklist.status': ['rencana', 'proses', 'selesai'],
  'units.status': ['rencana', 'persiapan', 'siap uji', 'siap buka', 'aktif'],
  'documents.status': ['belum ada', 'diproses', 'tersedia'],
  'risks.status': ['terbuka', 'ditangani', 'ditutup'],
  'issues.status': ['terbuka', 'ditangani', 'ditutup'],
  'staff.status': ['direncanakan', 'ditunjuk', 'aktif', 'nonaktif'],
  'trainings.status': ['rencana', 'selesai'],
  priority: ['rendah', 'normal', 'tinggi', 'mendesak'],
  poac: ['planning', 'organizing', 'actuating', 'controlling'],
  recurrence: ['tidak', 'harian', 'mingguan', 'bulanan'],
  dimension: ['legalitas', 'fisik', 'sdm', 'sop', 'sistem'],
};
export const navigation = [
  ['/beranda', 'Beranda', '◉'],
  ['/hari-ini', 'Hari Ini', '☀'],
  ['/tugas', 'Tugas', '✓'],
  ['/proyek', 'Proyek', '▣'],
  ['/roadmap', 'Roadmap', '↗'],
  ['/kesiapan', 'Kesiapan', '☷'],
  ['/gerai', 'Gerai', '▦'],
  ['/pemangku', 'Pemangku', '◎'],
  ['/rapat', 'Rapat', '◇'],
  ['/dokumen', 'Dokumen', '▤'],
  ['/risiko', 'Risiko & isu', '△'],
  ['/tim', 'Tim', '♧'],
  ['/laporan', 'Laporan', '▥'],
  ['/jurnal', 'Jurnal kerja', '✎'],
  ['/pengaturan', 'Pengaturan', '⚙'],
  ['/panduan', 'Panduan', '?'],
] as const;
export const pages: Record<string, Entity[]> = {
  tugas: ['work-items'],
  kesiapan: ['checklist'],
  gerai: ['units'],
  pemangku: ['stakeholders', 'interactions'],
  rapat: ['meetings', 'decisions'],
  dokumen: ['documents'],
  risiko: ['risks', 'issues'],
  tim: ['staff', 'trainings'],
  jurnal: ['journal'],
  pengaturan: ['organization', 'workstreams'],
};
